---
- hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: create new users
    shell: for i in jen will matt sam ann dan kate bru; do sudo useradd -m $i; done

  - name: create new groups - management sales ops
    group:
      name: "{{ item }}"
      state: present
    loop:
     - management
     - sales
     - ops

  - name: add jen and will to all groups
    user:
      name: "{{ item }}"
      state: present
      groups: management, sales, ops
    loop:
    - jen
    - will

  - name: add matt, sam, ann, and dan to the sales group
    user:
      name: "{{ item }}"
      state: present
      groups: sales
    loop:
    - matt
    - sam
    - ann
    - dan

  - name: add kate and bru to the ops group
    user:
      name: "{{ item }}"
      state: present
      groups: ops
    loop:
    - kate
    - bru
    
  - name: delete all users
    shell: for u in jen will matt sam ann danny kate bru; do echo "$u"; userdel -r "$u"; done

  - name: delete all groups
    shell: for u in management sales ops; do echo "$u"; groupdel "$u"; done
